# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c00a0fac58ec57092792a95d2bcd14eb7284f2625049fbff5b3c573c60eed917c02c661272290363bf748c486de6a2fbc486565c007318c47d8e671635cf4b2

test:
  secret_key_base: 1382834ab7aa3e678ec65414a6f68bf64c824ae973a78131c479c721e52aeed7b8bf960c5c078cb72ed03cd82592af5774074038b3f1596fe4932ddc7453154d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
